* C-Maiki
The C-Maiki group specializes in topological data analysis.

Code for analysis is given, presentation & data is hidden.

** Environmental Data Analysis
** Microbiome Data Analysis
** Rapid Ohia Death Data Analysis 
* Folder Structure
All projects get their own folder
Each project uses a common data folder
** Analysis
*** Microbiome
**** Definitions
***** Species
      An organism with a certain DNA sequence
***** Sample
      A specific location
***** Abundance Table
      A matrix of Sample vs Species
      If [A[i,j] = n], then [There are n species i at sample j] 
**** Plots
**** Variables
** Project
* Code Structure 
** Microbiome
*** Classes
**** Microbiome
A Class to represent a microbiome.
***** Constructor
Takes in a path to the data and path to save figures.
***** Analysis Functions
****** Unifrac Distance
****** Bray Curtis Dissimilarity
***** Plotting Methods
****** Shannon Diversity
****** Beta Diversity
****** Alpha Diversity
****** Abundance Table
****** Distance Matrix
